services:
  server:
    container_name: my-backend
    image: my-backend-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${PORT}:${PORT}" 
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    container_name: mysql-db
    image: mysql:8.4.4
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - mysql_native_password=ON
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
